### Урок 3


#### 1. Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

##### а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

Ответ:

$A*B$ = $4\times 2$ и $4\times 2$

$B*A$ = $4\times 2$ и $4\times 2$

Произведения не определены

##### б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

Ответ:

$A*B$ = $2\times 5$ и $5\times 3$, произведение определено, размерность полученной матрицы $2\times 3$

$B*A$ = $5\times 3$ и $2\times 5$, произведение не определено

##### в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

Ответ:

$A*B$ = $8\times 3$ и $3\times 8$, произведение определено, размерность полученной матрицы $8\times 8$

$B*A$ = $3\times 8$ и $8\times 3$, произведение определено, размерность полученной матрицы $3\times 3$

##### г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Ответ:

$A*B$, $B*A$ - оба произведения определены, размерность полученной матрицы $4\times 4$

In [1]:
import numpy as np

#### 2. Найти сумму и произведение матриц $A=\begin{pmatrix} 1 & -2\\ 3 & 0 \end{pmatrix}$ и $B=\begin{pmatrix} 4 & -1\\ 0 & 5 \end{pmatrix}.$

In [7]:
a = np.array([[1,-2], [3,0]])
b = np.array([[4,-1], [0,5]])
sum_ab = a + b
sum_ab

array([[ 5, -3],
       [ 3,  5]])

In [6]:
mult_ab = np.dot(a, b)
mult_ab

array([[  4, -11],
       [ 12,  -3]])

#### 3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix} 1 & 7\\ 3 & -6 \end{pmatrix}$, $B=\begin{pmatrix} 0 & 5\\ 2 & -1 \end{pmatrix}$, $C=\begin{pmatrix} 2 & -4\\ 1 & 1 \end{pmatrix}.$

In [8]:
a = np.array([[1,7], [3,-6]])
b = np.array([[0,5], [2,-1]])
c = np.array([[2,-4], [1,1]])
linear_comb = (3 * a) + (-2 * b) + (4 * c)
linear_comb

array([[ 11,  -5],
       [  9, -12]])

#### 4. Дана матрица $A=\begin{pmatrix} 4 & 1\\ 5 & -2\\ 2 & 3 \end{pmatrix}$. Вычислить $AA^{T}$ и $A^{T}A$.

In [9]:
a = np.array([[4,1], [5,-2], [2,3]])
aT = a.T
aT

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [10]:
AAt = np.dot(a, aT)
AAt

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [11]:
AtA = np.dot(aT, a)
AtA

array([[45,  0],
       [ 0, 14]])

#### 5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [18]:
def mult_2matrix(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        return ValueError('произведение не определено')
    result = [ [0 for j in range(len(matrix2[0]))] for i in range(len(matrix1))]
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result

In [19]:
x = np.array([[5,4], [1,7], [12,8]])
y = np.array([[-3,2], [12,-6]])

print(f'Результат метода NumPy:\n {np.dot(x,y)}')
print(f'Результат функции mult_2matrix: \n {mult_2matrix(x,y)}')

Результат метода NumPy:
 [[ 33 -14]
 [ 81 -40]
 [ 60 -24]]
Результат функции mult_2matrix: 
 [[33, -14], [81, -40], [60, -24]]


### Урок 4



#### 1. Вычислить определитель:

##### a)
$$\begin{vmatrix} sinx & -cosx\\ cosx & sinx \end{vmatrix};$$

Ответ:

$det = sinx * sinx - (cosx * -cosx) = sin^2x + cos^2x = 1$

#### б)
$$\begin{vmatrix} 4 & 2 & 3\\ 0 & 5 & 1\\ 0 & 0 & 9 \end{vmatrix};$$

In [20]:
b = np.array([[4,2,3], [0,5,1], [0,0,9]])
det_b = np.linalg.det(b)
det_b

180.0

#### в)
$$\begin{vmatrix} 1 & 2 & 3\\ 4 & 5 & 6\\ 7 & 8 & 9 \end{vmatrix}.$$

In [22]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
det_c = round(np.linalg.det(c))
det_c

0

#### 2. Определитель матрицы $A$ равен $4$. Найти:

##### а) $det(A^{2})$;

$det(A^{2}) = det(AA) = det(A)*det(a) = 4 * 4 = 16$

##### б) $det(A^{T})$;

$det(A^{T}) = det(A) = 4$

##### в) $det(2A)$.

$det(2A) = det(A) * 2^n = 4 * 2^n$, n - кол-во строк в матрице

#### 3. Доказать, что матрица
$$\begin{pmatrix} -2 & 7 & -3\\ 4 & -14 & 6\\ -3 & 7 & 13 \end{pmatrix}$$

#### вырожденная.

In [23]:
a = np.array([[-2,7,-3], [4,-14,6], [-3,7,13]])
det_a = np.linalg.det(a)
det_a

0.0

Ответ: определитель вырожденной матрицы равен 0, т.о. данная матрица является вырожденной.

#### 4. Найти ранг матрицы:

##### а) $\begin{pmatrix} 1 & 2 & 3\\ 1 & 1 & 1\\ 2 & 3 & 4 \end{pmatrix};$

In [25]:
a1 = np.array([[1,2,3], [1,1,1], [2,3,4]])
rank_a1 = np.linalg.matrix_rank(a1)
rank_a1

2

##### б) $\begin{pmatrix} 0 & 0 & 2 & 1\\ 0 & 0 & 2 & 2\\ 0 & 0 & 4 & 3\\ 2 & 3 & 5 & 6 \end{pmatrix}.$

In [26]:
a2 = np.array([[0,0,2,1], [0,0,2,2], [0,0,4,3], [2,3,5,6]])
rank_a2 = np.linalg.matrix_rank(a2)
rank_a2

3